apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  template: 
    metadata: 
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: gmauriciobr/api01
          ports:
            - containerPort: 80
          resources:  
            requests:
              cpu: 10m
  replicas: 2
  selector:
    matchLabels:
      app: api